type station_name_t = {
    name_kanji: string;
    name_kana: string;
    name_romaji: string;
    group: string;
}

type station_relation = {
    start_s: string;
    end_s: string;
    via: string;
    distance: float;
    time: int;
}

type station_t = {
    name: string;
    station_distance: float;
    station_list: string list;
}

let display_info station_info = match station_info with
    {
        name_kanji = n_kan;
        name_kana = n_ka;
        name_romaji = n_ro;
        group = g;
    } -> g^", "^n_kan^"("^n_ka^")"

let station_w = {
    name_kanji = "茗荷谷";
    name_kana = "みょうがだに";
    name_romaji = "myougadani";
    group = "丸ノ内線"
}

let test1 = display_info station_w = "丸ノ内線, 茗荷谷(みょうがだに)"

let global_ekikan_list = [
{start_s="代々木上原"; end_s="代々木公園"; via="千代田線"; distance=1.0; time=2};
{start_s="代々木公園"; end_s="明治神宮前"; via="千代田線"; distance=1.2; time=2};
{start_s="明治神宮前"; end_s="表参道"; via="千代田線"; distance=0.9; time=2};
{start_s="表参道"; end_s="乃木坂"; via="千代田線"; distance=1.4; time=3};
{start_s="乃木坂"; end_s="赤坂"; via="千代田線"; distance=1.1; time=2};
{start_s="赤坂"; end_s="国会議事堂前"; via="千代田線"; distance=0.8; time=1};
{start_s="国会議事堂前"; end_s="霞ヶ関"; via="千代田線"; distance=0.7; time=1};
{start_s="霞ヶ関"; end_s="日比谷"; via="千代田線"; distance=1.2; time=2};
{start_s="日比谷"; end_s="二重橋前"; via="千代田線"; distance=0.7; time=1};
{start_s="二重橋前"; end_s="大手町"; via="千代田線"; distance=0.7; time=1};
{start_s="大手町"; end_s="新御茶ノ水"; via="千代田線"; distance=1.3; time=2};
{start_s="新御茶ノ水"; end_s="湯島"; via="千代田線"; distance=1.2; time=2};
{start_s="湯島"; end_s="根津"; via="千代田線"; distance=1.2; time=2};
{start_s="根津"; end_s="千駄木"; via="千代田線"; distance=1.0; time=2};
{start_s="千駄木"; end_s="西日暮里"; via="千代田線"; distance=0.9; time=1};
{start_s="西日暮里"; end_s="町屋"; via="千代田線"; distance=1.7; time=2};
{start_s="町屋"; end_s="北千住"; via="千代田線"; distance=2.6; time=3};
{start_s="北千住"; end_s="綾瀬"; via="千代田線"; distance=2.5; time=3};
{start_s="綾瀬"; end_s="北綾瀬"; via="千代田線"; distance=2.1; time=4};
{start_s="浅草"; end_s="田原町"; via="銀座線"; distance=0.8; time=2};
{start_s="田原町"; end_s="稲荷町"; via="銀座線"; distance=0.7; time=1};
{start_s="稲荷町"; end_s="上野"; via="銀座線"; distance=0.7; time=2};
{start_s="上野"; end_s="上野広小路"; via="銀座線"; distance=0.5; time=2};
{start_s="上野広小路"; end_s="末広町"; via="銀座線"; distance=0.6; time=1};
{start_s="末広町"; end_s="神田"; via="銀座線"; distance=1.1; time=2};
{start_s="神田"; end_s="三越前"; via="銀座線"; distance=0.7; time=1};
{start_s="三越前"; end_s="日本橋"; via="銀座線"; distance=0.6; time=2};
{start_s="日本橋"; end_s="京橋"; via="銀座線"; distance=0.7; time=2};
{start_s="京橋"; end_s="銀座"; via="銀座線"; distance=0.7; time=1};
{start_s="銀座"; end_s="新橋"; via="銀座線"; distance=0.9; time=2};
{start_s="新橋"; end_s="虎ノ門"; via="銀座線"; distance=0.8; time=2};
{start_s="虎ノ門"; end_s="溜池山王"; via="銀座線"; distance=0.6; time=2};
{start_s="溜池山王"; end_s="赤坂見附"; via="銀座線"; distance=0.9; time=2};
{start_s="赤坂見附"; end_s="青山一丁目"; via="銀座線"; distance=1.3; time=2};
{start_s="青山一丁目"; end_s="外苑前"; via="銀座線"; distance=0.7; time=2};
{start_s="外苑前"; end_s="表参道"; via="銀座線"; distance=0.7; time=1};
{start_s="表参道"; end_s="渋谷"; via="銀座線"; distance=1.3; time=1};
{start_s="渋谷"; end_s="表参道"; via="半蔵門線"; distance=1.3; time=2};
{start_s="表参道"; end_s="青山一丁目"; via="半蔵門線"; distance=1.4; time=2};
{start_s="青山一丁目"; end_s="永田町"; via="半蔵門線"; distance=1.3; time=2};
{start_s="永田町"; end_s="半蔵門"; via="半蔵門線"; distance=1.0; time=2};
{start_s="半蔵門"; end_s="九段下"; via="半蔵門線"; distance=1.6; time=2};
{start_s="九段下"; end_s="神保町"; via="半蔵門線"; distance=0.4; time=1};
{start_s="神保町"; end_s="大手町"; via="半蔵門線"; distance=1.7; time=3};
{start_s="大手町"; end_s="三越前"; via="半蔵門線"; distance=0.7; time=1};
{start_s="三越前"; end_s="水天宮前"; via="半蔵門線"; distance=1.3; time=2};
{start_s="水天宮前"; end_s="清澄白河"; via="半蔵門線"; distance=1.7; time=3};
{start_s="清澄白河"; end_s="住吉"; via="半蔵門線"; distance=1.9; time=3};
{start_s="住吉"; end_s="錦糸町"; via="半蔵門線"; distance=1.; time=2};
{start_s="錦糸町"; end_s="押上"; via="半蔵門線"; distance=1.4; time=2};
{start_s="中目黒"; end_s="恵比寿"; via="日比谷線"; distance=1.; time=2};
{start_s="恵比寿"; end_s="広尾"; via="日比谷線"; distance=1.5; time=3};
{start_s="広尾"; end_s="六本木"; via="日比谷線"; distance=1.7; time=3};
{start_s="六本木"; end_s="神谷町"; via="日比谷線"; distance=1.5; time=3};
{start_s="神谷町"; end_s="霞ヶ関"; via="日比谷線"; distance=1.3; time=2};
{start_s="霞ヶ関"; end_s="日比谷"; via="日比谷線"; distance=1.2; time=2};
{start_s="日比谷"; end_s="銀座"; via="日比谷線"; distance=0.4; time=1};
{start_s="銀座"; end_s="東銀座"; via="日比谷線"; distance=0.4; time=1};
{start_s="東銀座"; end_s="築地"; via="日比谷線"; distance=0.6; time=2};
{start_s="築地"; end_s="八丁堀"; via="日比谷線"; distance=1.; time=2};
{start_s="八丁堀"; end_s="茅場町"; via="日比谷線"; distance=0.5; time=1};
{start_s="茅場町"; end_s="人形町"; via="日比谷線"; distance=0.9; time=2};
{start_s="人形町"; end_s="小伝馬町"; via="日比谷線"; distance=0.6; time=1};
{start_s="小伝馬町"; end_s="秋葉原"; via="日比谷線"; distance=0.9; time=2};
{start_s="秋葉原"; end_s="仲御徒町"; via="日比谷線"; distance=1.; time=1};
{start_s="仲御徒町"; end_s="上野"; via="日比谷線"; distance=0.5; time=1};
{start_s="上野"; end_s="入谷"; via="日比谷線"; distance=1.2; time=2};
{start_s="入谷"; end_s="三ノ輪"; via="日比谷線"; distance=1.2; time=2};
{start_s="三ノ輪"; end_s="南千住"; via="日比谷線"; distance=0.8; time=2};
{start_s="南千住"; end_s="北千住"; via="日比谷線"; distance=1.8; time=3};
{start_s="池袋"; end_s="新大塚"; via="丸ノ内線"; distance=1.8; time=3};
{start_s="新大塚"; end_s="茗荷谷"; via="丸ノ内線"; distance=1.2; time=2};
{start_s="茗荷谷"; end_s="後楽園"; via="丸ノ内線"; distance=1.8; time=2};
{start_s="後楽園"; end_s="本郷三丁目"; via="丸ノ内線"; distance=0.8; time=1};
{start_s="本郷三丁目"; end_s="御茶ノ水"; via="丸ノ内線"; distance=0.8; time=1};
{start_s="御茶ノ水"; end_s="淡路町"; via="丸ノ内線"; distance=0.8; time=1};
{start_s="淡路町"; end_s="大手町"; via="丸ノ内線"; distance=0.9; time=2};
{start_s="大手町"; end_s="東京"; via="丸ノ内線"; distance=0.6; time=1};
{start_s="東京"; end_s="銀座"; via="丸ノ内線"; distance=1.1; time=2};
{start_s="銀座"; end_s="霞ヶ関"; via="丸ノ内線"; distance=1.0; time=2};
{start_s="霞ヶ関"; end_s="国会議事堂前"; via="丸ノ内線"; distance=0.7; time=1};
{start_s="国会議事堂前"; end_s="赤坂見附"; via="丸ノ内線"; distance=0.9; time=2};
{start_s="赤坂見附"; end_s="四ツ谷"; via="丸ノ内線"; distance=1.3; time=2};
{start_s="四ツ谷"; end_s="四谷三丁目"; via="丸ノ内線"; distance=1.0; time=2};
{start_s="四谷三丁目"; end_s="新宿御苑前"; via="丸ノ内線"; distance=0.9; time=1};
{start_s="新宿御苑前"; end_s="新宿三丁目"; via="丸ノ内線"; distance=0.7; time=1};
{start_s="新宿三丁目"; end_s="新宿"; via="丸ノ内線"; distance=0.3; time=1};
{start_s="新宿"; end_s="西新宿"; via="丸ノ内線"; distance=0.8; time=1};
{start_s="西新宿"; end_s="中野坂上"; via="丸ノ内線"; distance=1.1; time=2};
{start_s="中野坂上"; end_s="新中野"; via="丸ノ内線"; distance=1.1; time=2};
{start_s="新中野"; end_s="東高円寺"; via="丸ノ内線"; distance=1.0; time=1};
{start_s="東高円寺"; end_s="新高円寺"; via="丸ノ内線"; distance=0.9; time=1};
{start_s="新高円寺"; end_s="南阿佐ヶ谷"; via="丸ノ内線"; distance=1.2; time=2};
{start_s="南阿佐ヶ谷"; end_s="荻窪"; via="丸ノ内線"; distance=1.5; time=2};
{start_s="中野坂上"; end_s="中野新橋"; via="丸ノ内線"; distance=1.3; time=2};
{start_s="中野新橋"; end_s="中野富士見町"; via="丸ノ内線"; distance=0.6; time=1};
{start_s="中野富士見町"; end_s="方南町"; via="丸ノ内線"; distance=1.3; time=2};
{start_s="市ヶ谷"; end_s="四ツ谷"; via="南北線"; distance=1.0; time=2};
{start_s="四ツ谷"; end_s="永田町"; via="南北線"; distance=1.3; time=3};
{start_s="永田町"; end_s="溜池山王"; via="南北線"; distance=0.9; time=1};
{start_s="溜池山王"; end_s="六本木一丁目"; via="南北線"; distance=0.9; time=2};
{start_s="六本木一丁目"; end_s="麻布十番"; via="南北線"; distance=1.2; time=2};
{start_s="麻布十番"; end_s="白金高輪"; via="南北線"; distance=1.3; time=2};
{start_s="白金高輪"; end_s="白金台"; via="南北線"; distance=1.0; time=2};
{start_s="白金台"; end_s="目黒"; via="南北線"; distance=1.3; time=2};
{start_s="市ヶ谷"; end_s="飯田橋"; via="南北線"; distance=1.1 ; time=2};
{start_s="飯田橋"; end_s="後楽園"; via="南北線"; distance=1.4 ; time=2};
{start_s="後楽園"; end_s="東大前"; via="南北線"; distance=1.3 ; time=3};
{start_s="東大前"; end_s="本駒込"; via="南北線"; distance=0.9 ; time=2};
{start_s="本駒込"; end_s="駒込"; via="南北線"; distance=1.4; time=2};
{start_s="駒込"; end_s="西ヶ原"; via="南北線"; distance=1.4; time=2};
{start_s="西ヶ原"; end_s="王子"; via="南北線"; distance=1.0; time=2};
{start_s="王子"; end_s="王子神谷"; via="南北線"; distance=1.2; time=2};
{start_s="王子神谷"; end_s="志茂"; via="南北線"; distance=1.6; time=3};
{start_s="志茂"; end_s="赤羽岩淵"; via="南北線"; distance=1.1; time=2};
{start_s="西船橋" ; end_s="原木中山"; via="東西線"; distance=1.9; time=3};
{start_s="原木中山"; end_s="妙典"; via="東西線"; distance=2.1 ; time=2};
{start_s="妙典"; end_s="行徳"; via="東西線"; distance=1.3 ; time=2};
{start_s="行徳"; end_s="南行徳"; via="東西線"; distance=1.5 ; time=2};
{start_s="南行徳"; end_s="浦安" ; via="東西線"; distance=1.2 ; time=2};
{start_s="浦安" ; end_s="葛西"; via="東西線"; distance=1.9 ; time=2};
{start_s="葛西"; end_s="西葛西"; via="東西線"; distance=1.2 ; time=2};
{start_s="西葛西"; end_s="南砂町"; via="東西線"; distance=2.7 ; time=2};
{start_s="南砂町"; end_s="東陽町"; via="東西線"; distance=1.2 ; time=2};
{start_s="東陽町"; end_s="木場" ; via="東西線"; distance=0.9 ; time=1};
{start_s="木場"; end_s="門前仲町"; via="東西線"; distance=1.1 ; time=1};
{start_s="門前仲町"; end_s="茅場町"; via="東西線"; distance=1.8 ; time=2};
{start_s="茅場町"; end_s="日本橋"; via="東西線"; distance=0.5 ; time=1};
{start_s="日本橋"; end_s="大手町"; via="東西線"; distance=0.8 ; time=1};
{start_s="大手町"; end_s="竹橋"; via="東西線"; distance=1.0; time=2};
{start_s="竹橋"; end_s="九段下"; via="東西線"; distance=1.0; time=1};
{start_s="九段下"; end_s="飯田橋"; via="東西線"; distance=0.7; time=1};
{start_s="飯田橋"; end_s="神楽坂"; via="東西線"; distance=1.2; time=2};
{start_s="神楽坂"; end_s="早稲田"; via="東西線"; distance=1.2; time=2};
{start_s="早稲田"; end_s="高田馬場"; via="東西線"; distance=1.7; time=3};
{start_s="高田馬場"; end_s="落合"; via="東西線"; distance=1.9; time=3};
{start_s="落合"; end_s="中野"; via="東西線"; distance=2.0; time=3};
{start_s="新木場"; end_s="辰巳"; via="有楽町線"; distance=1.5; time=2};
{start_s="辰巳"; end_s="豊洲"; via="有楽町線"; distance=1.7; time=2};
{start_s="豊洲"; end_s="月島"; via="有楽町線"; distance=1.4; time=2};
{start_s="月島"; end_s="新富町"; via="有楽町線"; distance=1.3; time=2};
{start_s="新富町"; end_s="銀座一丁目"; via="有楽町線"; distance=0.7; time=1};
{start_s="銀座一丁目"; end_s="有楽町"; via="有楽町線"; distance=0.5; time=1};
{start_s="有楽町"; end_s="桜田門"; via="有楽町線"; distance=1.0; time=1};
{start_s="桜田門"; end_s="永田町"; via="有楽町線"; distance=0.9; time=2};
{start_s="永田町"; end_s="麹町"; via="有楽町線"; distance=0.9; time=1};
{start_s="麹町"; end_s="市ヶ谷"; via="有楽町線"; distance=0.9; time=1};
{start_s="市ヶ谷"; end_s="飯田橋"; via="有楽町線"; distance=1.1; time=2};
{start_s="飯田橋"; end_s="江戸川橋"; via="有楽町線"; distance=1.6; time=3};
{start_s="江戸川橋"; end_s="護国寺"; via="有楽町線"; distance=1.3; time=2};
{start_s="護国寺"; end_s="東池袋"; via="有楽町線"; distance=1.1; time=2};
{start_s="東池袋"; end_s="池袋"; via="有楽町線"; distance=2.0; time=2};
{start_s="池袋"; end_s="要町"; via="有楽町線"; distance=1.2; time=2};
{start_s="要町"; end_s="千川"; via="有楽町線"; distance=1.0; time=1};
{start_s="千川"; end_s="小竹向原"; via="有楽町線"; distance=1.0; time=2};
{start_s="小竹向原"; end_s="氷川台"; via="有楽町線"; distance=1.5; time=2};
{start_s="氷川台"; end_s="平和台"; via="有楽町線"; distance=1.4; time=2};
{start_s="平和台"; end_s="営団赤塚"; via="有楽町線"; distance=1.8; time=2};
{start_s="営団赤塚"; end_s="営団成増"; via="有楽町線"; distance=1.5; time=2};
{start_s="営団成増"; end_s="和光市"; via="有楽町線"; distance=2.1; time=3};
]

let global_ekimei_list = [
{name_kanji="代々木上原"; name_kana="よよぎうえはら"; name_romaji="yoyogiuehara"; group="千代田線"};
{name_kanji="代々木公園"; name_kana="よよぎこうえん"; name_romaji="yoyogikouen"; group="千代田線"};
{name_kanji="明治神宮前"; name_kana="めいじじんぐうまえ"; name_romaji="meijijinguumae"; group="千代田線"};
{name_kanji="表参道"; name_kana="おもてさんどう"; name_romaji="omotesandou"; group="千代田線"};
{name_kanji="乃木坂"; name_kana="のぎざか"; name_romaji="nogizaka"; group="千代田線"};
{name_kanji="赤坂"; name_kana="あかさか"; name_romaji="akasaka"; group="千代田線"};
{name_kanji="国会議事堂前"; name_kana="こっかいぎじどうまえ"; name_romaji="kokkaigijidoumae"; group="千代田線"};
{name_kanji="霞ヶ関"; name_kana="かすみがせき"; name_romaji="kasumigaseki"; group="千代田線"};
{name_kanji="日比谷"; name_kana="ひびや"; name_romaji="hibiya"; group="千代田線"};
{name_kanji="二重橋前"; name_kana="にじゅうばしまえ"; name_romaji="nijuubasimae"; group="千代田線"};
{name_kanji="大手町"; name_kana="おおてまち"; name_romaji="otemachi"; group="千代田線"};
{name_kanji="新御茶ノ水"; name_kana="しんおちゃのみず"; name_romaji="shin-ochanomizu"; group="千代田線"};
{name_kanji="湯島"; name_kana="ゆしま"; name_romaji="yushima"; group="千代田線"};
{name_kanji="根津"; name_kana="ねづ"; name_romaji="nedu"; group="千代田線"};
{name_kanji="千駄木"; name_kana="せんだぎ"; name_romaji="sendagi"; group="千代田線"};
{name_kanji="西日暮里"; name_kana="にしにっぽり"; name_romaji="nishinippori"; group="千代田線"};
{name_kanji="町屋"; name_kana="まちや"; name_romaji="machiya"; group="千代田線"};
{name_kanji="北千住"; name_kana="きたせんじゅ"; name_romaji="kitasenjyu"; group="千代田線"};
{name_kanji="綾瀬"; name_kana="あやせ"; name_romaji="ayase"; group="千代田線"};
{name_kanji="北綾瀬"; name_kana="きたあやせ"; name_romaji="kitaayase"; group="千代田線"};
{name_kanji="浅草"; name_kana="あさくさ"; name_romaji="asakusa"; group="銀座線"};
{name_kanji="田原町"; name_kana="たわらまち"; name_romaji="tawaramachi"; group="銀座線"};
{name_kanji="稲荷町"; name_kana="いなりちょう"; name_romaji="inaricho"; group="銀座線"};
{name_kanji="上野"; name_kana="うえの"; name_romaji="ueno"; group="銀座線"};
{name_kanji="上野広小路"; name_kana="うえのひろこうじ"; name_romaji="uenohirokoji"; group="銀座線"};
{name_kanji="末広町"; name_kana="すえひろちょう"; name_romaji="suehirocho"; group="銀座線"};
{name_kanji="神田"; name_kana="かんだ"; name_romaji="kanda"; group="銀座線"};
{name_kanji="三越前"; name_kana="みつこしまえ"; name_romaji="mitsukoshimae"; group="銀座線"};
{name_kanji="日本橋"; name_kana="にほんばし"; name_romaji="nihonbashi"; group="銀座線"};
{name_kanji="京橋"; name_kana="きょうばし"; name_romaji="kyobashi"; group="銀座線"};
{name_kanji="銀座"; name_kana="ぎんざ"; name_romaji="ginza"; group="銀座線"};
{name_kanji="新橋"; name_kana="しんばし"; name_romaji="shinbashi"; group="銀座線"};
{name_kanji="虎ノ門"; name_kana="とらのもん"; name_romaji="toranomon"; group="銀座線"};
{name_kanji="溜池山王"; name_kana="ためいけさんのう"; name_romaji="tameikesannou"; group="銀座線"};
{name_kanji="赤坂見附"; name_kana="あかさかみつけ"; name_romaji="akasakamitsuke"; group="銀座線"};
{name_kanji="青山一丁目"; name_kana="あおやまいっちょうめ"; name_romaji="aoyamaicchome"; group="銀座線"};
{name_kanji="外苑前"; name_kana="がいえんまえ"; name_romaji="gaienmae"; group="銀座線"};
{name_kanji="表参道"; name_kana="おもてさんどう"; name_romaji="omotesando"; group="銀座線"};
{name_kanji="渋谷"; name_kana="しぶや"; name_romaji="shibuya"; group="銀座線"};
{name_kanji="渋谷"; name_kana="しぶや"; name_romaji="shibuya"; group="半蔵門線"};
{name_kanji="表参道"; name_kana="おもてさんどう"; name_romaji="omotesandou"; group="半蔵門線"};
{name_kanji="青山一丁目"; name_kana="あおやまいっちょうめ"; name_romaji="aoyama-itchome"; group="半蔵門線"};
{name_kanji="永田町"; name_kana="ながたちょう"; name_romaji="nagatacho"; group="半蔵門線"};
{name_kanji="半蔵門"; name_kana="はんぞうもん"; name_romaji="hanzomon"; group="半蔵門線"};
{name_kanji="九段下"; name_kana="くだんした"; name_romaji="kudanshita"; group="半蔵門線"};
{name_kanji="神保町"; name_kana="じんぼうちょう"; name_romaji="jinbocho"; group="半蔵門線"};
{name_kanji="大手町"; name_kana="おおてまち"; name_romaji="otemachi"; group="半蔵門線"};
{name_kanji="三越前"; name_kana="みつこしまえ"; name_romaji="mitsukoshimae"; group="半蔵門線"};
{name_kanji="水天宮前"; name_kana="すいてんぐうまえ"; name_romaji="suitengumae"; group="半蔵門線"};
{name_kanji="清澄白河"; name_kana="きよすみしらかわ"; name_romaji="kiyosumi-shirakawa"; group="半蔵門線"};
{name_kanji="住吉"; name_kana="すみよし"; name_romaji="sumiyoshi"; group="半蔵門線"};
{name_kanji="錦糸町"; name_kana="きんしちょう"; name_romaji="kinshicho"; group="半蔵門線"};
{name_kanji="押上"; name_kana="おしあげ"; name_romaji="oshiage"; group="半蔵門線"};
{name_kanji="中目黒"; name_kana="なかめぐろ"; name_romaji="nakameguro"; group="日比谷線"};
{name_kanji="恵比寿"; name_kana="えびす"; name_romaji="ebisu"; group="日比谷線"};
{name_kanji="広尾"; name_kana="ひろお"; name_romaji="hiro"; group="日比谷線"};
{name_kanji="六本木"; name_kana="ろっぽんぎ"; name_romaji="roppongi"; group="日比谷線"};
{name_kanji="神谷町"; name_kana="かみやちょう"; name_romaji="kamiyacho"; group="日比谷線"};
{name_kanji="霞ヶ関"; name_kana="かすみがせき"; name_romaji="kasumigaseki"; group="日比谷線"};
{name_kanji="日比谷"; name_kana="ひびや"; name_romaji="hibiya"; group="日比谷線"};
{name_kanji="銀座"; name_kana="ぎんざ"; name_romaji="ginza"; group="日比谷線"};
{name_kanji="東銀座"; name_kana="ひがしぎんざ"; name_romaji="higashiginza"; group="日比谷線"};
{name_kanji="築地"; name_kana="つきじ"; name_romaji="tsukiji"; group="日比谷線"};
{name_kanji="八丁堀"; name_kana="はっちょうぼり"; name_romaji="hacchobori"; group="日比谷線"};
{name_kanji="茅場町"; name_kana="かやばちょう"; name_romaji="kayabacho"; group="日比谷線"};
{name_kanji="人形町"; name_kana="にんぎょうちょう"; name_romaji="ningyomachi"; group="日比谷線"};
{name_kanji="小伝馬町"; name_kana="こでんまちょう"; name_romaji="kodemmacho"; group="日比谷線"};
{name_kanji="秋葉原"; name_kana="あきはばら"; name_romaji="akihabara"; group="日比谷線"};
{name_kanji="仲御徒町"; name_kana="なかおかちまち"; name_romaji="nakaokachimachi"; group="日比谷線"};
{name_kanji="上野"; name_kana="うえの"; name_romaji="ueno"; group="日比谷線"};
{name_kanji="入谷"; name_kana="いりや"; name_romaji="iriya"; group="日比谷線"};
{name_kanji="三ノ輪"; name_kana="みのわ"; name_romaji="minowa"; group="日比谷線"};
{name_kanji="南千住"; name_kana="みなみせんじゅ"; name_romaji="minamisenju"; group="日比谷線"};
{name_kanji="北千住"; name_kana="きたせんじゅ"; name_romaji="kitasenju"; group="日比谷線"};
{name_kanji="池袋"; name_kana="いけぶくろ"; name_romaji="ikebukuro"; group="丸ノ内線"};
{name_kanji="新大塚"; name_kana="しんおおつか"; name_romaji="shinotsuka"; group="丸ノ内線"};
{name_kanji="茗荷谷"; name_kana="みょうがだに"; name_romaji="myogadani"; group="丸ノ内線"};
{name_kanji="後楽園"; name_kana="こうらくえん"; name_romaji="korakuen"; group="丸ノ内線"};
{name_kanji="本郷三丁目"; name_kana="ほんごうさんちょうめ"; name_romaji="hongosanchome"; group="丸ノ内線"};
{name_kanji="御茶ノ水"; name_kana="おちゃのみず"; name_romaji="ochanomizu"; group="丸ノ内線"};
{name_kanji="淡路町"; name_kana="あわじちょう"; name_romaji="awajicho"; group="丸ノ内線"};
{name_kanji="大手町"; name_kana="おおてまち"; name_romaji="otemachi"; group="丸ノ内線"};
{name_kanji="東京"; name_kana="とうきょう"; name_romaji="tokyo"; group="丸ノ内線"};
{name_kanji="銀座"; name_kana="ぎんざ"; name_romaji="ginza"; group="丸ノ内線"};
{name_kanji="霞ヶ関"; name_kana="かすみがせき"; name_romaji="kasumigaseki"; group="丸ノ内線"};
{name_kanji="国会議事堂前"; name_kana="こっかいぎじどうまえ"; name_romaji="kokkaigijidomae"; group="丸ノ内線"};
{name_kanji="赤坂見附"; name_kana="あかさかみつけ"; name_romaji="akasakamitsuke"; group="丸ノ内線"};
{name_kanji="四ツ谷"; name_kana="よつや"; name_romaji="yotsuya"; group="丸ノ内線"};
{name_kanji="四谷三丁目"; name_kana="よつやさんちょうめ"; name_romaji="yotsuyasanchome"; group="丸ノ内線"};
{name_kanji="新宿御苑前"; name_kana="しんじゅくぎょえんまえ"; name_romaji="shinjuku-gyoemmae"; group="丸ノ内線"};
{name_kanji="新宿三丁目"; name_kana="しんじゅくさんちょうめ"; name_romaji="shinjuku-sanchome"; group="丸ノ内線"};
{name_kanji="新宿"; name_kana="しんじゅく"; name_romaji="shinjuku"; group="丸ノ内線"};
{name_kanji="西新宿"; name_kana="にししんじゅく"; name_romaji="nishi-shinjuku"; group="丸ノ内線"};
{name_kanji="中野坂上"; name_kana="なかのさかうえ"; name_romaji="nakano-sakaue"; group="丸ノ内線"};
{name_kanji="新中野"; name_kana="しんなかの"; name_romaji="shin-nakano"; group="丸ノ内線"};
{name_kanji="東高円寺"; name_kana="ひがしこうえんじ"; name_romaji="higashi-koenji"; group="丸ノ内線"};
{name_kanji="新高円寺"; name_kana="しんこうえんじ"; name_romaji="shin-koenji"; group="丸ノ内線"};
{name_kanji="南阿佐ヶ谷"; name_kana="みなみあさがや"; name_romaji="minami-asagaya"; group="丸ノ内線"};
{name_kanji="荻窪"; name_kana="おぎくぼ"; name_romaji="ogikubo"; group="丸ノ内線"};
{name_kanji="中野新橋"; name_kana="なかのしんばし"; name_romaji="nakano-shimbashi"; group="丸ノ内線"};
{name_kanji="中野富士見町"; name_kana="なかのふじみちょう"; name_romaji="nakano-fujimicho"; group="丸ノ内線"};
{name_kanji="方南町"; name_kana="ほうなんちょう"; name_romaji="honancho"; group="丸ノ内線"};
{name_kanji="四ツ谷"; name_kana="よつや"; name_romaji="yotsuya"; group="南北線"};
{name_kanji="永田町"; name_kana="ながたちょう"; name_romaji="nagatacho"; group="南北線"};
{name_kanji="溜池山王"; name_kana="ためいけさんのう"; name_romaji="tameikesanno"; group="南北線"};
{name_kanji="六本木一丁目"; name_kana="ろっぽんぎいっちょうめ"; name_romaji="roppongiitchome"; group="南北線"};
{name_kanji="麻布十番"; name_kana="あざぶじゅうばん"; name_romaji="azabujuban"; group="南北線"};
{name_kanji="白金高輪"; name_kana="しろかねたかなわ"; name_romaji="shirokanetakanawa"; group="南北線"};
{name_kanji="白金台"; name_kana="しろかねだい"; name_romaji="shirokanedai"; group="南北線"};
{name_kanji="目黒"; name_kana="めぐろ"; name_romaji="meguro"; group="南北線"};
{name_kanji="市ヶ谷"; name_kana="いちがや"; name_romaji="ichigaya"; group="南北線"};
{name_kanji="飯田橋"; name_kana="いいだばし"; name_romaji="idabashi"; group="南北線"};
{name_kanji="後楽園"; name_kana="こうらくえん"; name_romaji="korakuen"; group="南北線"};
{name_kanji="東大前"; name_kana="とうだいまえ"; name_romaji="todaimae"; group="南北線"};
{name_kanji="本駒込"; name_kana="ほんこまごめ"; name_romaji="honkomagome"; group="南北線"};
{name_kanji="駒込"; name_kana="こまごめ"; name_romaji="komagome"; group="南北線"};
{name_kanji="西ヶ原"; name_kana="にしがはら"; name_romaji="nishigahara"; group="南北線"};
{name_kanji="王子"; name_kana="おうじ"; name_romaji="oji"; group="南北線"};
{name_kanji="王子神谷"; name_kana="おうじかみや"; name_romaji="ojikamiya"; group="南北線"};
{name_kanji="志茂"; name_kana="しも"; name_romaji="shimo"; group="南北線"};
{name_kanji="赤羽岩淵"; name_kana="あかばねいわぶち"; name_romaji="akabaneiwabuchi"; group="南北線"};
{name_kanji="西船橋"; name_kana="にしふなばし"; name_romaji="nishi-funabashi"; group="東西線"};
{name_kanji="原木中山"; name_kana="ばらきなかやま"; name_romaji="baraki-nakayama"; group="東西線"};
{name_kanji="妙典"; name_kana="みょうでん"; name_romaji="myoden"; group="東西線"};
{name_kanji="行徳"; name_kana="ぎょうとく"; name_romaji="gyotoku"; group="東西線"};
{name_kanji="南行徳"; name_kana="みなみぎょうとく"; name_romaji="minami-gyotoku"; group="東西線"};
{name_kanji="浦安"; name_kana="うらやす"; name_romaji="urayasu"; group="東西線"};
{name_kanji="葛西"; name_kana="かさい"; name_romaji="kasai"; group="東西線"};
{name_kanji="西葛西"; name_kana="にしかさい"; name_romaji="nishi-kasai"; group="東西線"};
{name_kanji="南砂町"; name_kana="みなみすなまち"; name_romaji="minami-sunamachi"; group="東西線"};
{name_kanji="東陽町"; name_kana="とうようちょう"; name_romaji="touyoucho"; group="東西線"};
{name_kanji="木場"; name_kana="きば"; name_romaji="kiba"; group="東西線"};
{name_kanji="門前仲町"; name_kana="もんぜんなかちょう"; name_romaji="monzen-nakacho"; group="東西線"};
{name_kanji="茅場町"; name_kana="かやばちょう"; name_romaji="kayabacho"; group="東西線"};
{name_kanji="日本橋"; name_kana="にほんばし"; name_romaji="nihonbashi"; group="東西線"};
{name_kanji="大手町"; name_kana="おおてまち"; name_romaji="otemachi"; group="東西線"};
{name_kanji="竹橋"; name_kana="たけばし"; name_romaji="takebashi"; group="東西線"};
{name_kanji="九段下"; name_kana="くだんした"; name_romaji="kudanshita"; group="東西線"};
{name_kanji="飯田橋"; name_kana="いいだばし"; name_romaji="iidabashi"; group="東西線"};
{name_kanji="神楽坂"; name_kana="かぐらざか"; name_romaji="kagurazaka"; group="東西線"};
{name_kanji="早稲田"; name_kana="わせだ"; name_romaji="waseda"; group="東西線"};
{name_kanji="高田馬場"; name_kana="たかだのばば"; name_romaji="takadanobaba"; group="東西線"};
{name_kanji="落合"; name_kana="おちあい"; name_romaji="ochiai"; group="東西線"};
{name_kanji="中野"; name_kana="なかの"; name_romaji="nakano"; group="東西線"};
{name_romaji="shinkiba"; name_kana="しんきば"; name_kanji="新木場"; group="有楽町線"};
{name_romaji="tatsumi"; name_kana="たつみ"; name_kanji="辰巳"; group="有楽町線"};
{name_romaji="toyosu"; name_kana="とよす"; name_kanji="豊洲"; group="有楽町線"};
{name_romaji="tsukishima"; name_kana="つきしま"; name_kanji="月島"; group="有楽町線"};
{name_romaji="shintomityou"; name_kana="しんとみちょう"; name_kanji="新富町"; group="有楽町線"};
{name_romaji="ginzaittyoume"; name_kana="ぎんざいっちょうめ"; name_kanji="銀座一丁目"; group="有楽町線"};
{name_romaji="yuurakutyou"; name_kana="ゆうらくちょう"; name_kanji="有楽町"; group="有楽町線"};
{name_romaji="sakuradamon"; name_kana="さくらだもん"; name_kanji="桜田門"; group="有楽町線"};
{name_romaji="nagatacho"; name_kana="ながたちょう"; name_kanji="永田町"; group="有楽町線"};
{name_romaji="koujimachi"; name_kana="こうじまち"; name_kanji="麹町"; group="有楽町線"};
{name_romaji="ichigaya"; name_kana="いちがや"; name_kanji="市ヶ谷"; group="有楽町線"};
{name_romaji="iidabashi"; name_kana="いいだばし"; name_kanji="飯田橋"; group="有楽町線"};
{name_kanji="江戸川橋"; name_kana="えどがわばし"; name_romaji="edogawabasi"; group="有楽町線"};
{name_kanji="護国寺"; name_kana="ごこくじ"; name_romaji="gokokuji"; group="有楽町線"};
{name_kanji="東池袋"; name_kana="ひがしいけぶくろ"; name_romaji="higasiikebukuro"; group="有楽町線"};
{name_kanji="池袋"; name_kana="いけぶくろ"; name_romaji="ikebukuro"; group="有楽町線"};
{name_kanji="要町"; name_kana="かなめちょう"; name_romaji="kanametyou"; group="有楽町線"};
{name_kanji="千川"; name_kana="せんかわ"; name_romaji="senkawa"; group="有楽町線"};
{name_kanji="小竹向原"; name_kana="こたけむかいはら"; name_romaji="kotakemukaihara"; group="有楽町線"};
{name_kanji="氷川台"; name_kana="ひかわだい"; name_romaji="hikawadai"; group="有楽町線"};
{name_kanji="平和台"; name_kana="へいわだい"; name_romaji="heiwadai"; group="有楽町線"};
{name_kanji="営団赤塚"; name_kana="えいだんあかつか"; name_romaji="eidanakakuka"; group="有楽町線"};
{name_kanji="営団成増"; name_kana="えいだんなります"; name_romaji="eidannarimasu"; group="有楽町線"};
{name_kanji="和光市"; name_kana="わこうし"; name_romaji="wakousi"; group="有楽町線"}
]

(*
#use "metro.ml";;
*)